# sources.py — curated documentation URLs for each engineering domain.
#
# Structure:
#   SOURCES[category] = {
#       "title": human-readable label,
#       "pages": [(url, page_title), ...]
#   }
#
# Prefer single-page / print-friendly URLs where available (the Rust books
# and GNU manuals are complete single-page HTML, making extraction cleaner).

SOURCES = {

    # ─── Software Development ────────────────────────────────────────────────

    "software/rust": {
        "title": "Rust Programming Language",
        "pages": [
            ("https://doc.rust-lang.org/book/print.html",
             "The Rust Programming Language Book"),
            ("https://doc.rust-lang.org/rust-by-example/print.html",
             "Rust by Example"),
            ("https://doc.rust-lang.org/reference/print.html",
             "Rust Language Reference"),
            ("https://doc.rust-lang.org/cargo/print.html",
             "The Cargo Book"),
            ("https://doc.rust-lang.org/rustdoc/print.html",
             "The Rustdoc Book"),
            ("https://doc.rust-lang.org/nomicon/print.html",
             "The Rustonomicon (unsafe Rust)"),
            ("https://doc.rust-lang.org/edition-guide/print.html",
             "Rust Edition Guide"),
        ],
    },

    "software/javascript": {
        "title": "JavaScript / Node.js",
        "pages": [
            ("https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
             "MDN JavaScript Guide"),
            ("https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects",
             "MDN JS Global Objects Reference"),
            ("https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements",
             "MDN JS Statements Reference"),
            ("https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions",
             "MDN JS Functions Reference"),
            ("https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes",
             "MDN JS Classes Reference"),
            ("https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators",
             "MDN JS Operators Reference"),
            ("https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_management",
             "MDN JS Memory Management"),
            ("https://developer.mozilla.org/en-US/docs/Web/JavaScript/Event_loop",
             "MDN JS Event Loop"),
            ("https://nodejs.org/en/docs/guides",
             "Node.js Guides"),
            ("https://nodejs.org/api/documentation.html",
             "Node.js API Overview"),
            ("https://nodejs.org/api/fs.html",
             "Node.js File System API"),
            ("https://nodejs.org/api/net.html",
             "Node.js Net API"),
            ("https://nodejs.org/api/http.html",
             "Node.js HTTP API"),
            ("https://nodejs.org/api/stream.html",
             "Node.js Streams API"),
            ("https://nodejs.org/api/worker_threads.html",
             "Node.js Worker Threads"),
        ],
    },

    "software/python": {
        "title": "Python 3",
        "pages": [
            ("https://docs.python.org/3/tutorial/index.html",
             "Python Tutorial"),
            ("https://docs.python.org/3/tutorial/classes.html",
             "Python Classes"),
            ("https://docs.python.org/3/tutorial/errors.html",
             "Python Exceptions"),
            ("https://docs.python.org/3/tutorial/modules.html",
             "Python Modules"),
            ("https://docs.python.org/3/tutorial/stdlib.html",
             "Python Standard Library Tour"),
            ("https://docs.python.org/3/library/stdtypes.html",
             "Python Built-in Types"),
            ("https://docs.python.org/3/library/functions.html",
             "Python Built-in Functions"),
            ("https://docs.python.org/3/library/exceptions.html",
             "Python Exceptions Reference"),
            ("https://docs.python.org/3/library/concurrent.futures.html",
             "Python concurrent.futures"),
            ("https://docs.python.org/3/library/asyncio.html",
             "Python asyncio"),
            ("https://docs.python.org/3/library/subprocess.html",
             "Python subprocess"),
            ("https://docs.python.org/3/library/pathlib.html",
             "Python pathlib"),
            ("https://docs.python.org/3/library/dataclasses.html",
             "Python dataclasses"),
            ("https://docs.python.org/3/library/typing.html",
             "Python typing module"),
            ("https://docs.python.org/3/reference/datamodel.html",
             "Python Data Model"),
            ("https://peps.python.org/pep-0008/",
             "PEP 8 – Style Guide"),
            ("https://peps.python.org/pep-0020/",
             "PEP 20 – The Zen of Python"),
        ],
    },

    "software/c": {
        "title": "C Programming Language",
        "pages": [
            ("https://en.cppreference.com/w/c/language",
             "C Language Reference"),
            ("https://en.cppreference.com/w/c/header",
             "C Standard Library Headers"),
            ("https://en.cppreference.com/w/c/string/byte",
             "C String Functions"),
            ("https://en.cppreference.com/w/c/memory",
             "C Memory Management"),
            ("https://en.cppreference.com/w/c/io",
             "C File I/O"),
            ("https://en.cppreference.com/w/c/numeric/math",
             "C Math Functions"),
            ("https://en.cppreference.com/w/c/thread",
             "C Thread Support"),
            ("https://en.cppreference.com/w/c/error",
             "C Error Handling"),
        ],
    },

    "software/cpp": {
        "title": "C++ Programming Language",
        "pages": [
            ("https://en.cppreference.com/w/cpp/language",
             "C++ Language Reference"),
            ("https://en.cppreference.com/w/cpp/container",
             "C++ STL Containers"),
            ("https://en.cppreference.com/w/cpp/algorithm",
             "C++ STL Algorithms"),
            ("https://en.cppreference.com/w/cpp/memory",
             "C++ Memory Management"),
            ("https://en.cppreference.com/w/cpp/thread",
             "C++ Thread Support"),
            ("https://en.cppreference.com/w/cpp/utility",
             "C++ Utility Library"),
            ("https://en.cppreference.com/w/cpp/ranges",
             "C++ Ranges (C++20)"),
            ("https://en.cppreference.com/w/cpp/concepts",
             "C++ Concepts (C++20)"),
            ("https://en.cppreference.com/w/cpp/coroutine",
             "C++ Coroutines (C++20)"),
            ("https://isocpp.org/wiki/faq/",
             "ISO C++ FAQ"),
        ],
    },

    "software/golang": {
        "title": "Go Programming Language",
        "pages": [
            ("https://go.dev/doc/effective_go",
             "Effective Go"),
            ("https://go.dev/ref/spec",
             "Go Language Specification"),
            ("https://go.dev/doc/code",
             "How to Write Go Code"),
            ("https://go.dev/doc/faq",
             "Go FAQ"),
            ("https://go.dev/doc/tutorial/getting-started",
             "Getting Started with Go"),
            ("https://go.dev/doc/tutorial/web-service-gin",
             "Go REST API Tutorial"),
            ("https://go.dev/doc/tutorial/generics",
             "Go Generics Tutorial"),
            ("https://go.dev/doc/tutorial/workspaces",
             "Go Workspaces Tutorial"),
        ],
    },

    "software/java": {
        "title": "Java Programming Language",
        "pages": [
            ("https://dev.java/learn/",
             "Java Learning Center"),
            ("https://dev.java/learn/getting-started/",
             "Java Getting Started"),
            ("https://dev.java/learn/oop/",
             "Java OOP"),
            ("https://dev.java/learn/generics/",
             "Java Generics"),
            ("https://dev.java/learn/lambdas/",
             "Java Lambdas & Functional Programming"),
            ("https://dev.java/learn/streams/",
             "Java Streams API"),
            ("https://dev.java/learn/concurrency/",
             "Java Concurrency"),
            ("https://dev.java/learn/modules/",
             "Java Module System"),
            ("https://dev.java/learn/records/",
             "Java Records"),
            ("https://dev.java/learn/sealed-classes/",
             "Java Sealed Classes"),
        ],
    },

    "software/zig": {
        "title": "Zig Programming Language",
        "pages": [
            ("https://ziglang.org/documentation/master/",
             "Zig Language Reference"),
            ("https://ziglearn.org/chapter-0/",
             "Zig Learn – Introduction"),
            ("https://ziglearn.org/chapter-1/",
             "Zig Learn – Basics"),
            ("https://ziglearn.org/chapter-2/",
             "Zig Learn – Standard Library"),
            ("https://ziglearn.org/chapter-3/",
             "Zig Learn – Build System"),
            ("https://ziglearn.org/chapter-4/",
             "Zig Learn – Working with C"),
            ("https://ziglang.org/documentation/master/std/",
             "Zig Standard Library"),
        ],
    },

    "software/bash": {
        "title": "Bash Shell Scripting",
        "pages": [
            ("https://www.gnu.org/software/bash/manual/bash.html",
             "GNU Bash Reference Manual"),
            ("https://tldp.org/LDP/abs/html/index.html",
             "Advanced Bash-Scripting Guide (index)"),
            ("https://tldp.org/LDP/abs/html/part1.html",
             "ABS Part 1 – Introduction"),
            ("https://tldp.org/LDP/abs/html/part2.html",
             "ABS Part 2 – Basics of Scripting"),
            ("https://tldp.org/LDP/abs/html/part3.html",
             "ABS Part 3 – Beyond Basics"),
            ("https://tldp.org/LDP/abs/html/part4.html",
             "ABS Part 4 – Advanced Topics"),
            ("https://mywiki.wooledge.org/BashGuide",
             "Wooledge Bash Guide"),
            ("https://mywiki.wooledge.org/BashFAQ",
             "Wooledge Bash FAQ"),
            ("https://mywiki.wooledge.org/BashPitfalls",
             "Wooledge Bash Pitfalls"),
        ],
    },

    # ─── Database Engineering ─────────────────────────────────────────────────

    "database/postgresql": {
        "title": "PostgreSQL",
        "pages": [
            ("https://www.postgresql.org/docs/current/tutorial.html",
             "PostgreSQL Tutorial"),
            ("https://www.postgresql.org/docs/current/sql.html",
             "PostgreSQL SQL Reference"),
            ("https://www.postgresql.org/docs/current/datatype.html",
             "PostgreSQL Data Types"),
            ("https://www.postgresql.org/docs/current/functions.html",
             "PostgreSQL Functions & Operators"),
            ("https://www.postgresql.org/docs/current/indexes.html",
             "PostgreSQL Indexes"),
            ("https://www.postgresql.org/docs/current/performance-tips.html",
             "PostgreSQL Performance Tips"),
            ("https://www.postgresql.org/docs/current/runtime-config.html",
             "PostgreSQL Server Configuration"),
            ("https://www.postgresql.org/docs/current/backup.html",
             "PostgreSQL Backup & Restore"),
            ("https://www.postgresql.org/docs/current/managing-databases.html",
             "PostgreSQL Database Management"),
            ("https://www.postgresql.org/docs/current/user-manag.html",
             "PostgreSQL User Management"),
            ("https://www.postgresql.org/docs/current/parallel-query.html",
             "PostgreSQL Parallel Query"),
            ("https://www.postgresql.org/docs/current/wal.html",
             "PostgreSQL Write-Ahead Logging (WAL)"),
            ("https://www.postgresql.org/docs/current/monitoring.html",
             "PostgreSQL Monitoring"),
            ("https://www.postgresql.org/docs/current/plpgsql.html",
             "PostgreSQL PL/pgSQL"),
            ("https://www.postgresql.org/docs/current/extend.html",
             "PostgreSQL Extensions"),
        ],
    },

    "database/replication": {
        "title": "Database Replication & High Availability",
        "pages": [
            ("https://www.postgresql.org/docs/current/high-availability.html",
             "PostgreSQL High Availability Overview"),
            ("https://www.postgresql.org/docs/current/warm-standby.html",
             "PostgreSQL Warm Standby"),
            ("https://www.postgresql.org/docs/current/hot-standby.html",
             "PostgreSQL Hot Standby"),
            ("https://www.postgresql.org/docs/current/logical-replication.html",
             "PostgreSQL Logical Replication"),
            ("https://www.postgresql.org/docs/current/different-replication-solutions.html",
             "Replication Solutions Comparison"),
            ("https://www.postgresql.org/docs/current/protocol-replication.html",
             "PostgreSQL Streaming Replication Protocol"),
            ("https://patroni.readthedocs.io/en/latest/",
             "Patroni HA for PostgreSQL"),
            ("https://pgbackrest.org/user-guide.html",
             "pgBackRest User Guide"),
            ("https://repmgr.org/docs/current/",
             "repmgr Replication Manager"),
        ],
    },

    "database/infrastructure": {
        "title": "Database Infrastructure & Operations",
        "pages": [
            ("https://use-the-index-luke.com/",
             "Use The Index, Luke (Query Optimization)"),
            ("https://www.postgresql.org/docs/current/diskusage.html",
             "PostgreSQL Disk Usage"),
            ("https://www.postgresql.org/docs/current/kernel-resources.html",
             "PostgreSQL Kernel Resources"),
            ("https://pgbouncer.org/usage.html",
             "PgBouncer Connection Pooling"),
            ("https://pgbouncer.org/config.html",
             "PgBouncer Configuration"),
            ("https://www.postgresql.org/docs/current/explicit-locking.html",
             "PostgreSQL Locking"),
            ("https://www.postgresql.org/docs/current/mvcc.html",
             "PostgreSQL MVCC"),
            ("https://www.postgresql.org/docs/current/routine-vacuuming.html",
             "PostgreSQL Vacuuming"),
        ],
    },

    # ─── DevOps & Infrastructure ──────────────────────────────────────────────

    "devops/terraform": {
        "title": "Terraform (HashiCorp IaC)",
        "pages": [
            ("https://developer.hashicorp.com/terraform/language",
             "Terraform Language Overview"),
            ("https://developer.hashicorp.com/terraform/language/settings",
             "Terraform Settings"),
            ("https://developer.hashicorp.com/terraform/language/resources",
             "Terraform Resources"),
            ("https://developer.hashicorp.com/terraform/language/resources/behavior",
             "Terraform Resource Behavior"),
            ("https://developer.hashicorp.com/terraform/language/data-sources",
             "Terraform Data Sources"),
            ("https://developer.hashicorp.com/terraform/language/modules",
             "Terraform Modules"),
            ("https://developer.hashicorp.com/terraform/language/modules/syntax",
             "Terraform Module Syntax"),
            ("https://developer.hashicorp.com/terraform/language/state",
             "Terraform State"),
            ("https://developer.hashicorp.com/terraform/language/state/remote",
             "Terraform Remote State"),
            ("https://developer.hashicorp.com/terraform/language/expressions",
             "Terraform Expressions"),
            ("https://developer.hashicorp.com/terraform/language/functions",
             "Terraform Built-in Functions"),
            ("https://developer.hashicorp.com/terraform/language/values",
             "Terraform Variables, Locals, Outputs"),
            ("https://developer.hashicorp.com/terraform/language/providers",
             "Terraform Providers"),
            ("https://developer.hashicorp.com/terraform/language/backend",
             "Terraform Backends"),
            ("https://developer.hashicorp.com/terraform/cli",
             "Terraform CLI Reference"),
            ("https://developer.hashicorp.com/terraform/language/checks",
             "Terraform Checks & Preconditions"),
            ("https://developer.hashicorp.com/terraform/language/import",
             "Terraform Import"),
        ],
    },

    "devops/ansible": {
        "title": "Ansible Automation",
        "pages": [
            ("https://docs.ansible.com/ansible/latest/getting_started/index.html",
             "Ansible Getting Started"),
            ("https://docs.ansible.com/ansible/latest/playbook_guide/index.html",
             "Ansible Playbooks Guide"),
            ("https://docs.ansible.com/ansible/latest/inventory_guide/index.html",
             "Ansible Inventory"),
            ("https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html",
             "Ansible Variables"),
            ("https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html",
             "Ansible Loops"),
            ("https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_conditionals.html",
             "Ansible Conditionals"),
            ("https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_handlers.html",
             "Ansible Handlers"),
            ("https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_roles.html",
             "Ansible Roles"),
            ("https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_templating.html",
             "Ansible Jinja2 Templating"),
            ("https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_filters.html",
             "Ansible Filters"),
            ("https://docs.ansible.com/ansible/latest/collections_guide/index.html",
             "Ansible Collections"),
            ("https://docs.ansible.com/ansible/latest/vault_guide/index.html",
             "Ansible Vault"),
            ("https://docs.ansible.com/ansible/latest/network_guide/index.html",
             "Ansible Network Automation"),
            ("https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_async.html",
             "Ansible Async Tasks"),
            ("https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_strategies.html",
             "Ansible Execution Strategies"),
            ("https://docs.ansible.com/ansible/latest/tips_tricks/ansible_tips_tricks.html",
             "Ansible Tips & Tricks"),
        ],
    },

    "devops/proxmox": {
        "title": "Proxmox Virtual Environment",
        "pages": [
            ("https://pve.proxmox.com/pve-docs/pve-admin-guide.html",
             "Proxmox VE Admin Guide"),
            ("https://pve.proxmox.com/wiki/Cluster_Manager",
             "Proxmox Cluster Manager"),
            ("https://pve.proxmox.com/wiki/Storage",
             "Proxmox Storage"),
            ("https://pve.proxmox.com/wiki/Network_Configuration",
             "Proxmox Network Configuration"),
            ("https://pve.proxmox.com/wiki/Backup_and_Restore",
             "Proxmox Backup & Restore"),
            ("https://pve.proxmox.com/wiki/High_Availability",
             "Proxmox High Availability"),
            ("https://pve.proxmox.com/wiki/ZFS_on_Linux",
             "Proxmox ZFS"),
            ("https://pve.proxmox.com/wiki/Ceph_Server",
             "Proxmox Ceph Storage"),
            ("https://pve.proxmox.com/wiki/Qemu/KVM_Virtual_Machines",
             "Proxmox KVM Virtual Machines"),
            ("https://pve.proxmox.com/wiki/Linux_Container",
             "Proxmox LXC Containers"),
            ("https://pve.proxmox.com/wiki/Proxmox_VE_API",
             "Proxmox REST API"),
            ("https://pve.proxmox.com/wiki/Proxmox_Backup_Server",
             "Proxmox Backup Server"),
        ],
    },

    "devops/docker": {
        "title": "Docker & Containers",
        "pages": [
            ("https://docs.docker.com/get-started/overview/",
             "Docker Overview"),
            ("https://docs.docker.com/engine/reference/commandline/cli/",
             "Docker CLI Reference"),
            ("https://docs.docker.com/compose/",
             "Docker Compose"),
            ("https://docs.docker.com/engine/userguide/storagedriver/",
             "Docker Storage Drivers"),
            ("https://docs.docker.com/network/",
             "Docker Networking"),
            ("https://docs.docker.com/engine/security/",
             "Docker Security"),
            ("https://docs.docker.com/language/",
             "Docker Language Guides"),
        ],
    },

    # ─── Network Engineering ──────────────────────────────────────────────────

    "network/fundamentals": {
        "title": "Network Engineering Fundamentals",
        "pages": [
            ("https://www.cloudflare.com/learning/network-layer/what-is-the-network-layer/",
             "Network Layer"),
            ("https://www.cloudflare.com/learning/ddos/glossary/open-systems-interconnection-model-osi/",
             "OSI Model"),
            ("https://www.cloudflare.com/learning/network-layer/what-is-a-subnet/",
             "Subnetting & CIDR"),
            ("https://www.cloudflare.com/learning/network-layer/what-is-ipv6/",
             "IPv6"),
            ("https://www.cloudflare.com/learning/network-layer/what-is-a-router/",
             "Routers & Routing"),
            ("https://www.cloudflare.com/learning/network-layer/what-is-mtu/",
             "MTU"),
            ("https://www.cloudflare.com/learning/dns/what-is-dns/",
             "DNS"),
            ("https://www.cloudflare.com/learning/cdn/glossary/bgp/",
             "BGP"),
            ("https://www.cloudflare.com/learning/security/glossary/what-is-a-firewall/",
             "Firewalls"),
            ("https://www.cloudflare.com/learning/access-management/what-is-a-vpn/",
             "VPN"),
            ("https://www.cloudflare.com/learning/ddos/glossary/tcp-ip/",
             "TCP/IP Model"),
            ("https://www.cloudflare.com/learning/ssl/what-is-https/",
             "HTTPS & TLS"),
            ("https://www.cloudflare.com/learning/cdn/glossary/what-is-load-balancing/",
             "Load Balancing"),
        ],
    },

    "network/linux": {
        "title": "Linux Network Configuration",
        "pages": [
            ("https://linux-ip.net/html/",
             "Linux Advanced IP Routing & Traffic Control"),
            ("https://www.kernel.org/doc/html/latest/networking/ip-sysctl.html",
             "Linux Kernel IP Sysctl Reference"),
            ("https://nftables.org/projects/nftables/reference-manual.html",
             "nftables Reference Manual"),
            ("https://www.man7.org/linux/man-pages/man8/ip.8.html",
             "ip(8) man page"),
            ("https://www.man7.org/linux/man-pages/man8/ss.8.html",
             "ss(8) man page"),
            ("https://www.man7.org/linux/man-pages/man8/tc.8.html",
             "tc(8) Traffic Control man page"),
            ("https://wiki.archlinux.org/title/Network_configuration",
             "Arch Wiki – Network Configuration"),
        ],
    },

    # ─── IoT Protocols ───────────────────────────────────────────────────────

    "iot/mqtt": {
        "title": "MQTT Protocol",
        "pages": [
            ("https://mqtt.org/mqtt-specification/",
             "MQTT Specification Overview"),
            ("https://www.hivemq.com/mqtt-essentials/",
             "HiveMQ MQTT Essentials"),
            ("https://www.hivemq.com/mqtt-essentials/part-1-introducing-mqtt/",
             "MQTT Introduction"),
            ("https://www.hivemq.com/mqtt-essentials/part-2-publish-subscribe/",
             "MQTT Publish/Subscribe"),
            ("https://www.hivemq.com/mqtt-essentials/part-3-client-broker-connection-establishment/",
             "MQTT Client-Broker Connection"),
            ("https://www.hivemq.com/mqtt-essentials/part-4-mqtt-publish-subscribe-unsubscribe/",
             "MQTT Pub/Sub/Unsub"),
            ("https://www.hivemq.com/mqtt-essentials/part-5-mqtt-topics-best-practices/",
             "MQTT Topics & Best Practices"),
            ("https://www.hivemq.com/mqtt-essentials/part-6-mqtt-quality-of-service-levels/",
             "MQTT QoS Levels"),
            ("https://www.hivemq.com/mqtt-essentials/part-7-persistent-session-queuing-messages/",
             "MQTT Persistent Sessions"),
            ("https://www.hivemq.com/mqtt-essentials/part-8-retained-messages/",
             "MQTT Retained Messages"),
            ("https://www.hivemq.com/mqtt-essentials/part-9-last-will-and-testament/",
             "MQTT Last Will & Testament"),
            ("https://www.hivemq.com/mqtt-essentials/part-10-alive-client-take-over/",
             "MQTT Keep Alive"),
            ("https://www.hivemq.com/mqtt-essentials/part-11-mqtt-over-websockets/",
             "MQTT over WebSockets"),
            ("https://mosquitto.org/documentation/",
             "Eclipse Mosquitto Documentation"),
            ("https://mosquitto.org/man/mosquitto-conf-5.html",
             "Mosquitto Configuration Reference"),
            ("https://mosquitto.org/man/mosquitto-8.html",
             "Mosquitto Broker man page"),
            ("https://www.emqx.com/en/blog/the-easiest-guide-to-getting-started-with-mqtt",
             "EMQ X MQTT Getting Started Guide"),
            ("https://www.emqx.com/en/blog/mqtt5-new-features-cleaner-session-and-session-expiry-interval",
             "MQTT 5.0 New Features"),
            ("https://www.emqx.com/en/blog/mqtt-security-best-practices",
             "MQTT Security Best Practices"),
        ],
    },

    "iot/coap": {
        "title": "CoAP Protocol",
        "pages": [
            ("https://coap.technology/",
             "CoAP Technology Overview"),
            ("https://www.rfc-editor.org/rfc/rfc7252",
             "RFC 7252 – The Constrained Application Protocol (CoAP)"),
            ("https://www.rfc-editor.org/rfc/rfc8323",
             "RFC 8323 – CoAP over TCP/TLS/WebSockets"),
            ("https://www.rfc-editor.org/rfc/rfc7641",
             "RFC 7641 – CoAP Observing Resources"),
            ("https://www.rfc-editor.org/rfc/rfc7959",
             "RFC 7959 – CoAP Block-Wise Transfers"),
            ("https://libcoap.net/doc/reference/4.3.0/",
             "libcoap Reference Documentation"),
        ],
    },

    "iot/protocols": {
        "title": "IoT Protocols & Standards",
        "pages": [
            ("https://www.amqp.org/about/what",
             "AMQP Protocol Overview"),
            ("https://www.rabbitmq.com/tutorials/amqp-concepts.html",
             "RabbitMQ AMQP Concepts"),
            ("https://www.rabbitmq.com/docs/protocols",
             "RabbitMQ Protocol Support"),
            ("https://www.rabbitmq.com/docs/mqtt",
             "RabbitMQ MQTT Plugin"),
            ("https://opcfoundation.org/developer-tools/documents/unified-architecture/",
             "OPC-UA Unified Architecture Overview"),
            ("https://www.eclipse.org/leshan/",
             "Eclipse Leshan LwM2M Overview"),
            ("https://www.omaspecworks.org/what-is-oma-specworks/iot/lightweight-m2m-lwm2m/",
             "LwM2M – Lightweight M2M Protocol"),
            ("https://www.modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf",
             "Modbus Application Protocol Spec"),
            ("https://www.w3.org/TR/wot-thing-description/",
             "W3C Web of Things (WoT) Thing Description"),
            ("https://www.w3.org/TR/wot-architecture/",
             "W3C Web of Things Architecture"),
        ],
    },

    "iot/platforms": {
        "title": "IoT Platform Engineering",
        "pages": [
            ("https://docs.aws.amazon.com/iot/latest/developerguide/what-is-aws-iot.html",
             "AWS IoT Core Overview"),
            ("https://docs.aws.amazon.com/iot/latest/developerguide/iot-message-broker.html",
             "AWS IoT Message Broker"),
            ("https://docs.aws.amazon.com/iot/latest/developerguide/iot-rules.html",
             "AWS IoT Rules Engine"),
            ("https://docs.aws.amazon.com/iot/latest/developerguide/iot-security-identity.html",
             "AWS IoT Security & Identity"),
            ("https://docs.aws.amazon.com/iot/latest/developerguide/iot-device-shadows.html",
             "AWS IoT Device Shadows"),
            ("https://www.influxdata.com/time-series-platform/",
             "InfluxDB Time Series Platform"),
            ("https://docs.influxdata.com/influxdb/v2/write-data/",
             "InfluxDB Write Data"),
            ("https://docs.influxdata.com/influxdb/v2/query-data/flux/",
             "InfluxDB Flux Query Language"),
            ("https://grafana.com/docs/grafana/latest/dashboards/",
             "Grafana Dashboards"),
            ("https://prometheus.io/docs/introduction/overview/",
             "Prometheus Monitoring Overview"),
            ("https://prometheus.io/docs/concepts/data_model/",
             "Prometheus Data Model"),
            ("https://prometheus.io/docs/querying/basics/",
             "PromQL Query Basics"),
        ],
    },

    "iot/edge": {
        "title": "Edge Computing & IoT Gateway",
        "pages": [
            ("https://www.eclipse.org/kura/",
             "Eclipse Kura IoT Gateway Framework"),
            ("https://docs.edgexfoundry.org/3.1/",
             "EdgeX Foundry Platform Docs"),
            ("https://docs.edgexfoundry.org/3.1/microservices/device/sdk/sdk-api-overview/",
             "EdgeX Device SDK Overview"),
            ("https://www.balena.io/docs/learn/welcome/introduction/",
             "Balena Edge Fleet Management"),
            ("https://k3s.io/",
             "K3s Lightweight Kubernetes for Edge"),
            ("https://docs.k3s.io/",
             "K3s Documentation"),
            ("https://openfaas.com/docs/",
             "OpenFaaS Serverless for Edge"),
            ("https://nodered.org/docs/",
             "Node-RED Flow-based IoT Programming"),
            ("https://nodered.org/docs/user-guide/",
             "Node-RED User Guide"),
        ],
    },

    # ─── GitLab ───────────────────────────────────────────────────────────────

    "devops/gitlab": {
        "title": "GitLab CI/CD & DevOps Platform",
        "pages": [
            ("https://docs.gitlab.com/ee/ci/",
             "GitLab CI/CD Overview"),
            ("https://docs.gitlab.com/ee/ci/yaml/",
             "GitLab CI/CD YAML Reference"),
            ("https://docs.gitlab.com/ee/ci/variables/",
             "GitLab CI/CD Variables"),
            ("https://docs.gitlab.com/ee/ci/environments/",
             "GitLab Environments & Deployments"),
            ("https://docs.gitlab.com/ee/ci/pipelines/",
             "GitLab Pipelines"),
            ("https://docs.gitlab.com/ee/ci/pipelines/pipeline_architectures.html",
             "GitLab Pipeline Architectures"),
            ("https://docs.gitlab.com/ee/ci/jobs/",
             "GitLab CI Jobs"),
            ("https://docs.gitlab.com/ee/ci/runners/",
             "GitLab Runners Overview"),
            ("https://docs.gitlab.com/runner/",
             "GitLab Runner Documentation"),
            ("https://docs.gitlab.com/runner/configuration/advanced-configuration.html",
             "GitLab Runner Advanced Configuration"),
            ("https://docs.gitlab.com/ee/ci/docker/",
             "GitLab CI with Docker"),
            ("https://docs.gitlab.com/ee/ci/docker/using_docker_build.html",
             "GitLab CI Docker Build"),
            ("https://docs.gitlab.com/ee/user/packages/container_registry/",
             "GitLab Container Registry"),
            ("https://docs.gitlab.com/ee/topics/git/",
             "GitLab Git Topics"),
            ("https://docs.gitlab.com/ee/api/rest/",
             "GitLab REST API"),
            ("https://docs.gitlab.com/ee/api/graphql/",
             "GitLab GraphQL API"),
            ("https://docs.gitlab.com/ee/user/project/merge_requests/",
             "GitLab Merge Requests"),
            ("https://docs.gitlab.com/ee/user/project/protected_branches.html",
             "GitLab Protected Branches"),
            ("https://docs.gitlab.com/ee/administration/",
             "GitLab Administration"),
            ("https://docs.gitlab.com/ee/topics/autodevops/",
             "GitLab Auto DevOps"),
        ],
    },

    # ─── Kubernetes ───────────────────────────────────────────────────────────

    "devops/kubernetes": {
        "title": "Kubernetes Container Orchestration",
        "pages": [
            ("https://kubernetes.io/docs/concepts/overview/",
             "Kubernetes Overview"),
            ("https://kubernetes.io/docs/concepts/workloads/",
             "Kubernetes Workloads"),
            ("https://kubernetes.io/docs/concepts/workloads/pods/",
             "Kubernetes Pods"),
            ("https://kubernetes.io/docs/concepts/workloads/controllers/deployment/",
             "Kubernetes Deployments"),
            ("https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/",
             "Kubernetes StatefulSets"),
            ("https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/",
             "Kubernetes DaemonSets"),
            ("https://kubernetes.io/docs/concepts/services-networking/service/",
             "Kubernetes Services"),
            ("https://kubernetes.io/docs/concepts/services-networking/ingress/",
             "Kubernetes Ingress"),
            ("https://kubernetes.io/docs/concepts/storage/persistent-volumes/",
             "Kubernetes Persistent Volumes"),
            ("https://kubernetes.io/docs/concepts/configuration/configmap/",
             "Kubernetes ConfigMaps"),
            ("https://kubernetes.io/docs/concepts/configuration/secret/",
             "Kubernetes Secrets"),
            ("https://kubernetes.io/docs/concepts/security/rbac-good-practices/",
             "Kubernetes RBAC Best Practices"),
            ("https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/",
             "Kubernetes HPA"),
            ("https://kubernetes.io/docs/concepts/cluster-administration/networking/",
             "Kubernetes Networking"),
            ("https://kubernetes.io/docs/reference/kubectl/",
             "kubectl Reference"),
            ("https://helm.sh/docs/",
             "Helm Package Manager Docs"),
            ("https://helm.sh/docs/chart_template_guide/",
             "Helm Chart Template Guide"),
            ("https://kubernetes.io/docs/concepts/extend-kubernetes/operator/",
             "Kubernetes Operators"),
        ],
    },

    # ─── Security ─────────────────────────────────────────────────────────────

    "security/general": {
        "title": "Application & Infrastructure Security",
        "pages": [
            ("https://owasp.org/www-project-top-ten/",
             "OWASP Top 10"),
            ("https://owasp.org/www-project-api-security/",
             "OWASP API Security Top 10"),
            ("https://owasp.org/www-community/attacks/",
             "OWASP Attack Categories"),
            ("https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html",
             "OWASP Authentication Cheat Sheet"),
            ("https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html",
             "OWASP Authorization Cheat Sheet"),
            ("https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html",
             "OWASP Input Validation Cheat Sheet"),
            ("https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Security_Cheat_Sheet.html",
             "OWASP TLS Cheat Sheet"),
            ("https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html",
             "OWASP Docker Security Cheat Sheet"),
            ("https://cheatsheetseries.owasp.org/cheatsheets/Kubernetes_Security_Cheat_Sheet.html",
             "OWASP Kubernetes Security Cheat Sheet"),
            ("https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_Cheat_Sheet.html",
             "OWASP Secrets Management Cheat Sheet"),
            ("https://www.cloudflare.com/learning/ssl/what-is-ssl/",
             "What is SSL/TLS"),
            ("https://www.cloudflare.com/learning/ssl/what-is-a-tls-handshake/",
             "TLS Handshake Explained"),
            ("https://www.cloudflare.com/learning/ssl/types-of-ssl-certificates/",
             "SSL Certificate Types"),
            ("https://www.cloudflare.com/learning/access-management/what-is-oauth/",
             "OAuth 2.0 Explained"),
            ("https://www.cloudflare.com/learning/access-management/what-is-jwt/",
             "JWT Explained"),
            ("https://www.cloudflare.com/learning/access-management/what-is-zero-trust/",
             "Zero Trust Security"),
        ],
    },

    "security/iot": {
        "title": "IoT Security",
        "pages": [
            ("https://owasp.org/www-project-internet-of-things/",
             "OWASP IoT Project"),
            ("https://www.enisa.europa.eu/publications/guidelines-for-securing-the-internet-of-things",
             "ENISA IoT Security Guidelines"),
            ("https://www.nist.gov/system/files/documents/2020/05/12/nist_iot_report_2020.pdf",
             "NIST IoT Security Report"),
            ("https://www.hivemq.com/blog/mqtt-security-fundamentals-tls-ssl/",
             "MQTT TLS/SSL Security Fundamentals"),
            ("https://www.hivemq.com/blog/mqtt-security-fundamentals-authentication-username-password/",
             "MQTT Authentication"),
            ("https://www.hivemq.com/blog/mqtt-security-fundamentals-mqtt-authorization/",
             "MQTT Authorization"),
            ("https://www.hivemq.com/blog/mqtt-security-fundamentals-payload-encryption/",
             "MQTT Payload Encryption"),
            ("https://www.hivemq.com/blog/mqtt-security-fundamentals-mqtts-tls/",
             "MQTTS Deep Dive"),
            ("https://cheatsheetseries.owasp.org/cheatsheets/Network_Segmentation_Cheat_Sheet.html",
             "OWASP Network Segmentation Cheat Sheet"),
        ],
    },

    "security/devsecops": {
        "title": "DevSecOps & Supply Chain Security",
        "pages": [
            ("https://docs.gitlab.com/ee/user/application_security/",
             "GitLab Application Security"),
            ("https://docs.gitlab.com/ee/user/application_security/sast/",
             "GitLab SAST"),
            ("https://docs.gitlab.com/ee/user/application_security/dast/",
             "GitLab DAST"),
            ("https://docs.gitlab.com/ee/user/application_security/container_scanning/",
             "GitLab Container Scanning"),
            ("https://docs.gitlab.com/ee/user/application_security/dependency_scanning/",
             "GitLab Dependency Scanning"),
            ("https://docs.gitlab.com/ee/user/application_security/secret_detection/",
             "GitLab Secret Detection"),
            ("https://slsa.dev/spec/v1.0/",
             "SLSA Supply Chain Security Framework"),
            ("https://www.sigstore.dev/",
             "Sigstore Code Signing"),
            ("https://trivy.dev/latest/docs/",
             "Trivy Vulnerability Scanner Docs"),
            ("https://aquasecurity.github.io/trivy/",
             "Trivy Getting Started"),
            ("https://www.vaultproject.io/docs",
             "HashiCorp Vault Secrets Management"),
            ("https://developer.hashicorp.com/vault/docs/secrets",
             "HashiCorp Vault Secrets Engines"),
        ],
    },

    # ─── Team Lead & Engineering Management ──────────────────────────────────

    "management/engineering": {
        "title": "Engineering Leadership & Team Management",
        "pages": [
            ("https://www.atlassian.com/agile/scrum",
             "Scrum Framework Overview"),
            ("https://www.atlassian.com/agile/kanban",
             "Kanban Methodology"),
            ("https://www.atlassian.com/agile/project-management/metrics",
             "Agile Metrics"),
            ("https://docs.gitlab.com/ee/user/group/",
             "GitLab Groups & Team Management"),
            ("https://docs.gitlab.com/ee/user/project/code_owners.html",
             "GitLab Code Owners"),
            ("https://docs.gitlab.com/ee/development/code_review.html",
             "GitLab Code Review Guidelines"),
            ("https://www.conventionalcommits.org/en/v1.0.0/",
             "Conventional Commits Specification"),
            ("https://semver.org/",
             "Semantic Versioning Specification"),
            ("https://www.writerside.jetbrains.com/",
             "Technical Documentation Best Practices"),
            ("https://opensource.guide/best-practices/",
             "Open Source Best Practices for Maintainers"),
        ],
    },
}

# Convenience: flat list of all categories
ALL_CATEGORIES = sorted(SOURCES.keys())

# Domain groupings (for --domain filter)
DOMAINS = {
    "software":   [k for k in ALL_CATEGORIES if k.startswith("software/")],
    "database":   [k for k in ALL_CATEGORIES if k.startswith("database/")],
    "devops":     [k for k in ALL_CATEGORIES if k.startswith("devops/")],
    "network":    [k for k in ALL_CATEGORIES if k.startswith("network/")],
    "iot":        [k for k in ALL_CATEGORIES if k.startswith("iot/")],
    "security":   [k for k in ALL_CATEGORIES if k.startswith("security/")],
    "management": [k for k in ALL_CATEGORIES if k.startswith("management/")],
}
